# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "minecraft-server-prod-us-east-2-terraform-state"
    dynamodb_table = "terraform-minecraft-server-prod-us-east-2-terraform-state-table"
    encrypt        = true
    key            = "server/terraform.tfstate"
    region         = "us-east-2"
  }
}
