# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa

variable "env" {
  description = "Environment - (Generated by terragrunt)"
  default     = "prod"
}

variable "project" {
  description = "Project - (Generated by terragrunt)"
  default     = "minecraft-server-prod-us-east-2"
}

variable "project_name" {
  description = "Project Name- (Generated by terragrunt)"
  default     = "minecraft-server"
}

variable "region" {
  description = "Region - (Generated by terragrunt)"
  default     = "us-east-2"
}

variable "org" {
  description = "Organization - (Generated by terragrunt)"
  default     = "diegotony"
}

