# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa

variable "tg_common_tags" {
  description = "Common tags for all gcp resources - (Generated by terragrunt)"
  default = {
    env       = "prod"
    project   = "minecraft-server-prod-us-east-2"
    region    = "us-east-2"
    org       = "diegotony"
    createdBy = "diegotony"
  }
}

